### ISSUE TITLE
Unable to see the url after the browser launch

### ISSUE THREAD

**Issue by sjulakanti-BSFT** [navalkgupta/protractor-cucumber-tests#1]
Using command to run: D:\Automation\Collaboration_ATT> protractor conf.js

DevTools listening on ws://127.0.0.1:12817/devtools/browser/574ff8ec-2eae-46cf-9557-bb541beb415b
Unhandled rejection TypeError: registerHandler is not a function
    at D:\Automation\Collaboration_ATT\features\support\hooks.js:14:4
    at defineSupportCode (D:\Automation\Collaboration_ATT\node_modules\cucumber\src\support_code_library_builder\index.js:20:9)
    at Object.<anonymous> (D:\Automation\Collaboration_ATT\features\support\hooks.js:13:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at D:\Automation\Collaboration_ATT\node_modules\cucumber\src\cli\index.js:61:42
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (D:\Automation\Collaboration_ATT\node_modules\cucumber\src\cli\index.js:61:22)
    at Cli.<anonymous> (D:\Automation\Collaboration_ATT\node_modules\cucumber\src\cli\index.js:76:37)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (D:\Automation\Collaboration_ATT\node_modules\bluebird\js\release\util.js:16:23)

**Comment by navalkgupta** [comment]
Did you follow all the steps as per documentation, because if you have all the node modules installed in your project directory without changing any of the version, you should no see such issue
